# Generated by Django 4.0.3 on 2022-04-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('date_in', models.DateField(verbose_name='Date In')),
                ('date_out', models.DateField(verbose_name='Date Out')),
                ('max_guests', models.IntegerField(verbose_name='Max Guests')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('converted_price', models.IntegerField(verbose_name='Converted Price')),
                ('link', models.URLField(verbose_name='Offer Link')),
                ('picture', models.URLField(verbose_name='Image Link')),
            ],
        ),
    ]
